name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - name: create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: build-macos
    needs: ['create-release']
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: build libwg
        run: cd libwg && ./build.sh
      - name: build frontend
        run: cd web && npm install && npm run build
      - name: build package
        run: cargo build --release
      - name: build tarball
        run: |
          cd target
          cp release/corplink .
          tar -czf corplink-${{ github.ref_name }}-macos-$(uname -m).tar.gz corplink
      - name: upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/corplink-*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  build-linux:
    name: build-linux
    needs: ['create-release']
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: build libwg
        run: cd libwg && ./build.sh
      - name: build frontend
        run: cd web && npm install && npm run build
      - name: build package
        run: cargo build --release
      - name: build tarball
        run: |
          cd target
          cp release/corplink .
          tar -czf corplink-${{ github.ref_name }}-linux-$(uname -m).tar.gz corplink
      - name: upload tarball to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/corplink-*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  build-windows:
    name: build-windows
    needs: ['create-release']
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: build libwg
        run: cd libwg && ./build.ps1
      - name: build frontend
        run: cd web && npm install && npm run build
      - name: rust install gnu toolchain
        run: rustup toolchain install stable-gnu
      - name: rust use gnu toolchain
        run: rustup default stable-x86_64-pc-windows-gnu
      - name: build package
        run: cargo build --release
      - name: build check result
        run: |
          Move-Item -Path "target/release/corplink.exe" -Destination "."
          Compress-Archive -Path corplink.exe -Destination corplink-${{ github.ref_name }}-windows.zip
      - name: upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: corplink-${{ github.ref_name }}-windows.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
